# Bioconda's supported python versions are described
# in ../docs/source/user/versions.rst
# so please keep that documentation up to date as they change

# Additional bioconda-specific pinnings to use in addition to those specified
# in
# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

# clear hard-coded default value for CONDA_BUILD_SYSROOT
CONDA_BUILD_SYSROOT:
  - ""
MACOSX_DEPLOYMENT_TARGET:
  - "10.9"

pin_run_as_build:
  htslib:
    max_pin: x.x
  bamtools:
    max_pin: x.x.x
  r-base:
    max_pin: x.x
    min_pin: x.x

htslib:
  - "1.17"

bamtools:
  - "2.5.1"

# NOTE: Workaround https://github.com/conda/conda-build/issues/3974 we slightly alter the values
#       from conda-forge-pinnings here (inserting '.*' or ' ' which should be ignored later on).
r_base:
  - "4.3.*"

python:
  - 3.10.*  *_cpython
  - 3.9.*  *_cpython
  - 3.8.*  *_cpython

# conda-forge only has 3 python versions, so we need to modify the length of the other zip_keys in its group
python_impl:
  - cpython
  - cpython
  - cpython

# Warning! This needs to both match the length of python and python_impl but ALSO match what conda-forge is using/has used!
numpy:
  - 1.21.*
  - 1.21.*
  - 1.21.*

channel_sources:
  - conda-forge,bioconda,defaults

channel_targets:
  - bioconda main
