# Bioconda's supported python versions are described
# in ../docs/source/user/versions.rst
# so please keep that documentation up to date as they change

# Additional bioconda-specific pinnings to use in addition to those specified
# in
# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

# clear hard-coded default value for CONDA_BUILD_SYSROOT
CONDA_BUILD_SYSROOT:
  - ""
c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
c_stdlib_version:
  - 2.17                       # [linux]
  - 11.0                       # [osx and arm64]
  - 10.13                      # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 11.0                       # [osx and arm64]
  - 10.13                      # [osx and x86_64]

bamtools:
  - "2.5.3"

# NOTE: Workaround https://github.com/conda/conda-build/issues/3974 we slightly alter the values
#       from conda-forge-pinnings here (inserting '.*' or ' ' which should be ignored later on).
r_base:
  - "4.4.*"

# # conda-forge-pinning just got updated to build for Py 3.12 by default.
# # In case we want to drop 3.8 before conda-forge does, we can use the following:
# python:
#   - 3.12.*  *_cpython
#   - 3.11.*  *_cpython
#   - 3.10.*  *_cpython
#   - 3.9.*  *_cpython
#
# # Needs to match the length of the other zip_keys in its group (python, python_impl, numpy).
# python_impl:
#   - cpython
#   - cpython
#   - cpython
#   - cpython
#
# # Warning! This needs to both match the length of python and python_impl but ALSO match what conda-forge is using/has used!
# numpy:
#   - 1.26.*
#   - 1.23.*
#   - 1.22.*
#   - 1.22.*

channel_sources:
  - conda-forge,bioconda

channel_targets:
  - bioconda main
