requirements: requirements.txt
blacklists:
    - build-fail-blacklist
docker_image: "condaforge/linux-anvil-comp7"
docker_url: 'unix://var/run/docker.sock'
upload_channel: bioconda
channels:
    - conda-forge
    - bioconda
    - anaconda
