env_matrix: example_env_matrix.yml
requirements: requirements.txt
blacklists:
    - r-blacklist
docker_image: "condaforge/linux-anvil"
docker_url: 'unix://var/run/docker.sock'
upload_channel: bioconda
channels:
    - anaconda
    - conda-forge
    - bioconda
