ARG base

FROM "${base}"
RUN set -x && \
    CONDA_PKGS_DIRS="/tmp/pkgs" \
      /opt/create-env/env-execute \
        create-env \
          --conda=mamba \
          /usr/local \
          file findutils grep
RUN set -x && \
    . /usr/local/env-activate.sh && \
    if find /opt/create-env \
      -xdev \
      -type f \
      -exec file {} \+ \
      | grep 'not stripped' \
    ; then \
      >&2 printf 'found unstripped binaries\n' ; exit 1 \
    ; fi
RUN set -x && \
    . /usr/local/env-activate.sh && \
    if find /opt/create-env \
      -xdev \
      -type f \
      -name \*.a \
      | grep . \
    ; then \
      >&2 printf 'found static libraries\n' ; exit 1 \
    ; fi


FROM "${base}" as build_bioconda_package
RUN set -x && \
    /opt/create-env/env-execute \
      create-env \
        --conda=mamba \
        --strip-files=\* \
        /usr/local \
        catfasta2phyml
FROM quay.io/bioconda/base-glibc-busybox-bash
COPY --from=build_bioconda_package /usr/local /usr/local
RUN set -x && \
    /usr/local/env-execute \
      catfasta2phyml --version \
    && \
    [ ! "${CONDA_PREFIX}" = /usr/local ] \
    && \
    { set -x && . /usr/local/env-activate.sh && set +x ; } \
    && \
    [ "${CONDA_PREFIX}" = /usr/local ] \
    && \
    catfasta2phyml --version


FROM "${base}" as build_conda
RUN set -x && \
    /opt/create-env/env-execute \
      create-env \
        --conda=mamba \
        --env-activate-args='--prefix-is-base' \
        --strip-files=\* \
        --remove-paths=\*.a \
        --remove-paths=\*.pyc \
        /opt/conda \
        conda
FROM quay.io/bioconda/base-glibc-busybox-bash
COPY --from=build_conda /opt/conda /opt/conda
COPY --from=build_conda /opt/conda/env-activate.sh /usr/local/
RUN set -x && \
    /usr/local/env-execute \
      conda info --all \
    && \
    { set -x && . /usr/local/env-activate.sh && set +x ; } \
    && \
    . "${CONDA_PREFIX}/etc/profile.d/conda.sh" \
    && \
    conda activate \
    && \
    conda info \
      | grep 'base environment.*/opt/conda'
