name: Build image
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
    - '.circleci/**'
    - 'docs/**'
    - 'test/**'

jobs:
  build:
    name: Build image
    runs-on: ubuntu-24.04
    container:
      # travier/podman-action contains newer podman/buildah versions.
      image: quay.io/travier/podman-action
      options: --privileged
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Build and test image
      uses: ./.github/actions/build-bioconda-utils-container
      with:
        tags: ${{ github.sha }}
