on:
  push:
    branches:
      - master
  workflow_dispatch:

name: release-please

jobs:
  release_please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          release-type: python
          package-name: bioconda-utils

  publish_containers:
    runs-on: ubuntu-24.04
    container:
      # travier/podman-action contains newer podman/buildah versions.
      image: quay.io/travier/podman-action
      options: --privileged
    needs: release_please
    if: needs.release_please.outputs.release_created
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - id: get-tag
        run: |
          tag=${{ needs.release_please.outputs.tag_name }}
          printf %s "tag=${tag#v}" >> "${GITHUB_OUTPUT}"

      - name: Build and test image
        id: build
        uses: ./.github/actions/build-bioconda-utils-container
        with:
          tags: >-
            latest
            ${{ steps.get-tag.outputs.tag }}

      - name: Publish
        id: publish
        uses: ./.github/actions/publish-container
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          mutable-tags: latest
          # TODO: Store the public repository path as a GitHub variable instead of a secret.
          registry: ${{ vars.QUAY_BIOCONDA_REPO }}
          username: ${{ secrets.QUAY_BIOCONDA_USERNAME }}
          password: ${{ secrets.QUAY_BIOCONDA_TOKEN }}

      - name: Test Pushed
        shell: bash
        env:
          TEST_IMAGE: ${{ steps.publish.outputs.test-image }}
        run: |
          set -euxo pipefail
          .github/scripts/test-pushed-container Dockerfile.test .

          podman run --rm --pull=always --arch=amd64 "${TEST_IMAGE}" bioconda-utils --version
          podman run --rm --pull=always --arch=arm64 "${TEST_IMAGE}" bioconda-utils --version
